### ISSUE TITLE
Add trigger to calculate some dataset fields based on target table

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-pgmetadata-plugin#10]
These fields must be calculated by a trigger BEFORE

- feature_count -> count(*) FROM table
- geometry_type -> GeometryType(geom)
- projection_name -> 'RGF93 Lambert conformal conic' (voir table public.spatial_ref_sys avec un WHERE sur srid INFOS ?)
- projection_authid -> 'EPSG:2154'
- spatial_extent ->  'xmin,ymin,xmax,ymax'
- geom -> geometry containing all the features. Can be a simple polygon make from `ST_ConvexHull(geom)`

**Comment by Gustry** [comment]
Done in #12
