### ISSUE TITLE
form view editing auto-switches to first feature

### ISSUE THREAD

**Issue by zackarno** [3liz/qgis-pgmetadata-plugin#105]
Hello,

I noticed that when if  I have more than one table connected to the "Dataset" table in the QGIS pgmetadata manager project I cannot edit attributes under the attributes tab using form view. As soon as I enter a text box and begin typing the form automatically switches to the first feature in the "Dataset". This is also true for any of the other widgets- again it automatically switches to the first feature. I am able to edit all the data fine in table view however.

I am not sure if this is a bug or if I am just not understanding something. Thanks!

**Comment by zackarno** [comment]
The only work-around  I have found to edit features in form view is to `select` the feature then click `Show Selected Features` . After doing this I am able to edit features metadata in the form view. 

It seems like this is not the intended work-flow as it is not what occurs in the video demonstration tutorials. Also this is not an issue when editing other QGIS files in form view.

**Comment by effjot** [comment]
I’ve reinstalled old Qgis versions: 3.10 on my Debian machine at home and 3.16 on Windows at work. Both behave normally, whereas version 3.22 (at least since 3.22.5) on both OSes exhibits this issue.

**Comment by effjot** [comment]
The bug is gone in Qgis 3.24 (Tisler) :-)

**Comment by Gustry** [comment]
Thanks for checking
