### ISSUE TITLE
Create views to search tables not referenced in the dataset table & dataset items with no corresponding PostgreSQL table

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-pgmetadata-plugin#11]
The idea is to have 2 views allowing to control the orphas:

- [x] get all the lines in `pgmetadata.dataset` which point to tables that do not exists
- [x] get all the tables in the PostgreSQL database which are not yet referenced in the table `pgmetadata.dataset`
- [x] add these views in the administration project

**Comment by drillinP** [comment]
Commit 99f76d0b856829536610f8e22c768b8d0ecc9f62

**Comment by drillinP** [comment]
Commit 99f76d0b856829536610f8e22c768b8d0ecc9f62
