### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by vmx** [3liz/qgis-pgmetadata-plugin#113]
This project seems like it is an open source project. It would be great if you could add a license.

**Comment by effjot** [comment]
Maybe you could address this before your presentation at FOSS4G? I couldn’t find a license on Github or the PgMetadata website. too. I assume it’s licensed under the GPL, because it’s published on the Qgis plugin repo. It would be nice to mention it explicitly, though.

**Comment by mdouchin** [comment]
Thanks for the reminder ! It is now done: PgMetadata is released under the GNU General Public License v2.0

**Comment by effjot** [comment]
Development sprint for Firenze! ;-)
