### ISSUE TITLE
gh-pages branch confuses git on Windows because of files with same name, different case

### ISSUE THREAD

**Issue by effjot** [3liz/qgis-pgmetadata-plugin#114]
I accidentally checked out the gh-pages branch. I didn’t want to work on it, just get back to master.
However, I couldn’t switch back, because git on Windows always thinks the working directory has changed. There are 2 folders which each have 2 case variants (CONTRIBUTING, contributing, CHANGELOG, changelog), which Windows treats as one. So even after a `git reset`, uncommited changes appear, because one variant overwrites the other.

So far, I only wanted to get out of this branch, and I could do it with `git checkout -f master`. But in case anybody on Windows needs to work on this branch, it’ll get difficult.

**Comment by Gustry** [comment]
The `gh-pages` is managed by the CI/bot to build the website. All the source files are in the `master` branch in the `docs` folder so the branch shouldn't be checkout.

Hopefully, someone will look for existing tickets. Thanks for the info.

**Comment by effjot** [comment]
Thanks for the clarification! I will just delete it in my repository, because it appears next to `master` in the list of branches and I don’t want to again accidentally check it out ;-)
