### ISSUE TITLE
Some backslashes in links to files on Windows get mangled

### ISSUE THREAD

**Issue by effjot** [3liz/qgis-pgmetadata-plugin#115]
I’d like to put links to local Windows files (e.g. PDFs for further documentation) in the metadata. However, some (not all) backslashes in the path get removed. It seems to happen if a backslash precedes a number.

**Comment by Gustry** [comment]
Can you share some screenshots/example ? (source in the form versus HTML output ?)

**Comment by effjot** [comment]
I’ve already identified the culprit. The substitions strings for regexp_replace() can refer to subexpressions in the match pattern by \1 … \9.

You can have a look at https://github.com/effjot/qgis-pgmetadata-plugin/commit/3291e10521004fb3dfb0d0f853e36f63a911b230
If you like, I could prepare a PR tomorrow.

**Comment by effjot** [comment]
Also, I think the regexes could be simplified, as the capturing groups (round parentheses) and non-greedy quantifiers don’t seem to be necessary:

    concat('\[% *"*', item.col, '"* *%\])

Or even

    concat('\[% *"?', item.col, '"? *%\])

(assuming there should be at maximum one quote around the item).
