### ISSUE TITLE
Semicolons in connection names are illegal but user is not informed

### ISSUE THREAD

**Issue by effjot** [3liz/qgis-pgmetadata-plugin#120]
When looking into #119, I realised that semicolons in connection names won’t work with PgMetadata, because the semicolon is used as a separator in the `connection_names` setting. But they can be added in the Set Connections tool
I’d suggest the processing tool `set_connections.py` should tell the user that semicolons aren’t allowed and reject connecting the database.
Should I prepare a PR?

**Comment by Gustry** [comment]
Maybe we should switch to a more complex separator ? Such as `!!::!!` ?

**Comment by Gustry** [comment]
I was proposing `!!::!! ` because it's the one used by QGIS core, to separate items in a string ;-)
I can try to make it.

**Comment by effjot** [comment]
Ah, I  didn’t know that. Then this would be a good choice.
