### ISSUE TITLE
Add phone number field to contacts table

### ISSUE THREAD

**Issue by effjot** [3liz/qgis-pgmetadata-plugin#123]
We’d like to store phone numbers for contacts, too. Do you think this would be a useful addition in general? Then I’d prepare a pull request.

**Comment by effjot** [comment]
@Gustry I’ve added a phone number field. Also, I made the email adresse a clickable link (mailto) in the HTML template. Would you like me to prepare a PR?

**Comment by Gustry** [comment]
For the mailto, yes no problem, thanks.
For the phone number, indeed, it wasn't included in the plugin. QGIS has the field : https://github.com/qgis/QGIS/blob/master/resources/qgis-base-metadata.xsd#L129 Ok for me too I think. @mdouchin ?

**Comment by Gustry** [comment]
We are planning a release very soon, before the FOSS4G, there will be a talk https://talks.osgeo.org/foss4g-2022/talk/A3TBBA/

**Comment by mdouchin** [comment]
+1 for a PR. Thanks !

**Comment by effjot** [comment]
When I read about your talk, I tried to get those issues and PRs moving ;-)
