### ISSUE TITLE
HTML translation : organization

### ISSUE THREAD

**Issue by phicote** [3liz/qgis-pgmetadata-plugin#150]
In English “Organization” is written with a “z”.

**Comment by mdouchin** [comment]
I think `organisation` is the correct spelling for UK English. 
We could use organization instead, but I would not dare to start a language "fight" (colour/color, metre/meter, etc.)

**Comment by phicote** [comment]
I totally agree, don’t start the fight. I didn’t know the difference for that particular word.

**Comment by Gustry** [comment]
Yes, but I think the ticket is correct.
QGIS is following American English, PgMetadata should follow the same IMHO.

https://prowritingaid.com/organisation-vs-organization

> Organization is the only correct spelling of this word in American English, whilst both spellings are acceptable in British English.

QGIS server properties about "Organi*ation" :

![image](https://user-images.githubusercontent.com/1609292/221828053-e978647f-e9c6-4908-9392-109b46de7261.png)

QGIS global settings about the language :

![image](https://user-images.githubusercontent.com/1609292/221828139-864695a1-1fa3-4cea-a22b-2be6332c4fbf.png)
