### ISSUE TITLE
Generate PDF/HTML in a file

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-pgmetadata-plugin#18]
Next to the settings gear in the dock, we can have a save button, with a drop down menu : 
* Save as PDF
* Save as HTML

It would take the content of the HTML panel and save it into a file, with the given format.

**Comment by Gustry** [comment]
@drillinP If you want another task to do on PgMetadata, this one is seems a good one.

**Comment by Gustry** [comment]
I think we should add some margin to the PDF.

**Comment by drillinP** [comment]
> I think we should add some margin to the PDF.

ok, i look how to add some margin

**Comment by drillinP** [comment]
Commit d6e56e2ea3ebd414c510b8220fdf43596f7fdd51
