### ISSUE TITLE
Localization - Add localization capability

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-pgmetadata-plugin#20]
- [x] Add new fields with french translation in `glossary` : `label_fr` and `description_fr`
- [x] Add new table to store pgmetadata configuration, and add a locale field
- [x] Add an option with available languages in the `Create metadata administration project`: this will add a new project variable with pgmetadata locale and set the corresponding value in the new configuration table

**Comment by Gustry** [comment]
Note from #22 : 

According to the language of the user, the SQL should use a COALESCE to take if possible the correct translation on the SQL side

**Comment by Gustry** [comment]
From #51 

* [x] Add new fields label_fr and description_fr
* [x] Create a new view v_glossarywhich transforms the glossary data into a simple JSON
* [x] Use this view in the view v_contact, v_dataset & v_link and call the JSON with a session variable pgmetadata.locale
* [x] Modify the HTML export function(s) to set this variable via SET SESSION "pgmetadata.locale" = 'fr';

Done in master
* [x] Use this locale when calling the HTML function

Current PR : 
* [x] Add tests about SQL #51 

Not done : 
* [ ] Add a way to choose the locale within QGIS, for example with a combobox in the dock toolbar. I think I will just use the QGIS default language for now, no ?

**Comment by mdouchin** [comment]
@Gustry @drillinP I just pushed a new commit 44a066083b17206bf575207a2cdaee9dc33acd7d which

* add columns for label and description for 3 new languages: `it, en & de`
* add a view `pgmetadata.v_locales` wich lists the available locales
* change the function `pgmetadata.get_dataset_item_html_content`: make it insentitive to case (fr = FR) && use en if given locale is not available

**Comment by Gustry** [comment]
@mdouchin The QGIS translation process can take of the the Value Relation Widget !
Read the "Content translation" chapter.
https://www.opengis.ch/fr/2018/09/11/qgis-speaks-a-lot-of-languages/

In QtTranslator, I have set `label` is translated to `label_fr`:

![Screenshot from 2021-01-07 11-38-48](https://user-images.githubusercontent.com/1609292/103851750-bbc75f80-50aa-11eb-8fb0-e9941736b980.png)

I think it would nicer to switch from `label` to `label_en` ?

**Comment by mdouchin** [comment]
Nice ! +1 to use label_en

**Comment by Gustry** [comment]
Closing this one. This ticket is done now. The QGIS Project will be done with #30.
