### ISSUE TITLE
The locator should take care of orphan metadata

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-pgmetadata-plugin#31]
The locator shouldn't show orphan metadata

- [x] Add a view `pgmetadata.v_valid_dataset` which gives a list of lines from `pgmetadata.dataset` with corresponding (existing) tables. This view returns only `table_name` and `schema_name`, no need for a autogenerated id with `row_number`
- [x] In the Python `locator.py` use it in the existing SQL query: add a `INNER JOIN` to return only data for existing datasets
- [x] Add this view in the administration template project

**Comment by mdouchin** [comment]
@Gustry can we close ?
