### ISSUE TITLE
calculate_fields_from_data doesn't like geometries with Z or M

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-pgmetadata-plugin#32]
While inserting rows in the `dataset` table, the function `calculate_fields_from_data` doesn't like if the geometry has a Z or M dimension.
```
Geometry has Z dimension but column does not
```
calculate_fields_from_data line 51 execute

We need a test case with a layer having Z dimension

CC @drillinP @mdouchin

**Comment by mdouchin** [comment]
Should be fixex with 1642904
