### ISSUE TITLE
ST_ConvexHull might return point or line

### ISSUE THREAD

**Issue by Gustry** [3liz/qgis-pgmetadata-plugin#35]
On a point layer with
* a single feature, `ST_ConvexHull` will return a point
* two features, `ST_ConvexHull` will return a line string
* more features aligned, `ST_ConvexHull` will return a line string as well

The dataset table is expecting a polygon:

```
_core.QgsProviderConnectionException: SQL error: INSERT INTO pgmetadata.dataset (table_name,schema_name,title,abstract) VALUES ('test_geom_z','pgmetadata','Test title Z','Test abstract Z.') returned 0 [ERROR:  Geometry type (Point) does not match column type (Polygon)
CONTEXT:  PL/pgSQL function pgmetadata.calculate_fields_from_data() line 56 at EXECUTE
```

Low probability I know, but still a possible bug.

**Comment by mdouchin** [comment]
Indeed. In the SQL trigger, we have to check the `GeometryType(NEW.geom)` after having modified it. If it is not polygon, use `ST_Buffer(NEW.geom, 0.0001)`
