### ISSUE TITLE
Export all datasets as a table layer

### ISSUE THREAD

**Issue by mdouchin** [3liz/qgis-pgmetadata-plugin#60]
Since the commit 71109de there is a new function `pgmetadata.export_datasets_as_flat_table(_locale text)` which allows to get a flat version of the datasets. This could be used to add a "Export all" button which will create a new QGIS vector (table) layer by invoking `SELECT * FROM pgmetadata.export_datasets_as_flat_table(LOCALE)`

The user will be able to save this layers as LibreOffice Calc, or Microsoft Excel or CSV file via the "Save as" QGIS feature.

I think there are 2 places for this flat export:
* in the dock panel, for the average users: "Export all the catalog"
* in the admin project, as a pre-loaded layer

**Comment by Gustry** [comment]
This has been done https://docs.3liz.org/qgis-pgmetadata-plugin/user-guide/end-user/#export-the-catalog
