### ISSUE TITLE
support views

### ISSUE THREAD

**Issue by tschuettenberg** [3liz/qgis-pgmetadata-plugin#65]
Hi,
in order to support (geodata-/layer-)views you could use `information_schema.tables`[1] instead of `pg_tables` in 
- `v_valid_dataset`, 
- `v_orphan_tables` and 
- `v_orphan_dataset_items`

(like it is already in `pgmetadata.v_table_list`). 
It works on my side. Side effect: as `v_valid_dataset` is used by the locator code, views will also be found. 
Could make a PR, if you like.

[1] https://www.postgresql.org/docs/13/infoschema-tables.html

Great plugin!
Cheers

**Comment by Gustry** [comment]
A PR would be more than welcome.

And better if there is a test included :)
https://docs.3liz.org/qgis-pgmetadata-plugin/contributing/#code

I can help on the PR if needed (with the migration etc)

**Comment by tschuettenberg** [comment]
Ah, not only Update 30_VIEW.sql shoul be edited, but also a new `upgrade_to_1.0.1sql` containig the the same DDL, right?
But I don't know where to put the python-"switch" you are mentioning.
And I don't have a unittest environment at hand.

**Comment by Gustry** [comment]
> Ah, not only Update 30_VIEW.sql shoul be edited, but also a new upgrade_to_1.0.1sql

Yes, indeed.
This is needed to make the migration for already existing database.
1.1.0 as you are adding a new feature would be perfect.

> And I don't have a unittest environment at hand.

Ok no worries.
If you have docker, it's easy.

Can you make a pull request with your commits ?
