### ISSUE TITLE
German translation with Transifex

### ISSUE THREAD

**Issue by effjot** [3liz/qgis-pgmetadata-plugin#69]
I’d like to help with a German translation on Transifex. However, I cannot add it: after clicking “Join team” I only get offered French, and the hint says I should request a language that’s not offered. But when I click “Request language”, I cannot request German, because it is already marked “Requested language”.
Could you have a look into why German isn’t available in either option? Thanks!

**Comment by Gustry** [comment]
It should be ok now.

Thanks for translating this project !

Let me know if you have any issue.

**Comment by effjot** [comment]
Thanks for adding me to the translation team. I have finished the German translation and like to try it in my local copy of the plugin. However, I’m not familiar with the build process (my last experience was with PO/gettext quite a while ago…). I can only download a .ts file from Transifex, but I guess I need a .qm file instead. How can I build the .qm file?

**Comment by Gustry** [comment]
You need Qt `lrelease` to transform the *.ts to *.qm.

I just created a zip with translations to let you try.

[pg_metadata.1.1.0-alpha1.zip](https://github.com/3liz/qgis-pgmetadata-plugin/files/7045902/pg_metadata.1.1.0-alpha1.zip)

**Comment by effjot** [comment]
One more little thing: in `dock.py`, line 309

     'Missing metadata',

should get a `tr()`. Could you then update the Transifex project?

**Comment by Gustry** [comment]
Transifex is updated automatically from commits on master.

Feel free to provide a PR next time if needed.

Done in 871b481 Transifex will be updated within a minute.
