### ISSUE TITLE
Non-UTF8 characters prevent plugin set up

### ISSUE THREAD

**Issue by daviddehoog** [3liz/qgis-pgmetadata-plugin#76]
Using QGIS 3.16.6-Hannover and postgresql12 on MacOSX 11.5.2 (Big Sur). Plugin loads, but when running "installation of the database structure" and "create metadata administration project", each fails. Managed to install by removing non-UTF8 characters from 90_glossary.sql and pg_metadata_administration.qgs. These characters seemed to be French language characters and once replaced with UTF-8-like characters, both scripts ran fine.

**Comment by Gustry** [comment]
Can you try this zip ?
[pg_metadata.1.1.0-beta1.zip](https://github.com/3liz/qgis-pgmetadata-plugin/files/7090816/pg_metadata.1.1.0-beta1.zip)


If it's not working, you need to copy/paste the error when creating the database structure ?
Can you also copy/paste logs ? (PostGIS and PgMetadata tab) in the QGIS logs (some comic stip bubble in the bottom right corner)

Copy/paste your Help -> About table version as well.

Thanks

**Comment by daviddehoog** [comment]
The beta package install seems to fail, though it seems to have installed correctly, it has also installed a non-existent "__MACOSX" package. It looks like a path issue?

Couldn't load plugin '__MACOSX/pg_metadata' 

ModuleNotFoundError: No module named '__MACOSX/pg_metadata' 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 793, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named '__MACOSX/pg_metadata'

**Comment by daviddehoog** [comment]
Using the beta plugin works. Have successfully run a fresh "Installation of the database structure" and "Create metadata administration project".

**Comment by Gustry** [comment]
You can remove the `__MACOSX` folder in your plugin diretory.
Are you should use the QGIS Plugin manager to install a ZIP plugin ? I think it will avoid this MacOS folder.

So I'm closing, it will be fixed when we will release soon 1.1.0

**Comment by daviddehoog** [comment]
Many thanks! I did use the QGIS Plugin Manager to load the zip. Look forward to 1.1.0.
